Create SCHEMA Lasers;
USE Lasers;
CREATE TABLE LaserTbl (
  LaserId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  LaserName VARCHAR(10) NOT NULL,
  PRIMARY KEY (LaserId)
);
CREATE TABLE FaultTbl (
  FaultId INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
  FaultName VARCHAR(100) NOT NULL,
  FaultSolution TEXT NOT NULL,
  FaultDate DATE NOT NULL,
  LaserId TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (FaultId),
  FOREIGN KEY (LaserId) REFERENCES LaserTbl(LaserId)
);
